language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar
 - composer self-update
 - composer install

script:
 - phpunit --coverage-text

after_script:
  - php bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - info@gemini-project.net
  on_success: never
  on_failure: always

